### ISSUE TITLE
SessionStorage object won't array merge

### ISSUE THREAD

**Issue by basz** [zendframework/zend-session#10]
When I configure session storage to use the Zend\Session\Storage\SessionStorage::class which would replace the $_SESSION variable with an ArrayObject an fatal error occurs then the ArrayObject is fed into ArrayUtil:merge() as that will only accept an array.

```
 /* @see \Zend\Session\Storage\StorageInterface */
    'session_storage' => [
        'type' => \Zend\Session\Storage\SessionStorage::class,
    ],
```

```
Argument 1 passed to Zend\Stdlib\ArrayUtils::merge() must be of the type array, object given, called in ../vendor/zendframework/zend-session/src/SessionManager.php on line 114 and defined in <b>..../vendor/zendframework/zend-stdlib/src/ArrayUtils.php
```

I'm using zend-session 2.5.2

**Comment by Nakira** [comment]
Had to do this : (v2.7.3 and stldlib ) https://github.com/8trust/zend-session/commit/c5e523a4b661e3fb336bd009dc21f8edfe687270

Had a typeError:

```
Fatal error: Uncaught TypeError: Argument 1 passed to Zend\Stdlib\ArrayUtils::merge() must be of the type array, object given, called in /var/www/vendor/zendframework/zend-session/src/SessionManager.php on line 136 and defined in /var/www/vendor/zendframework/zend-stdlib/src/ArrayUtils.php:269
```

This also worked by remove the strong typing on merge method.
I'm sure i'm missing something here, but works with my fork.

**Comment by rogatec** [comment]
I resolved it with:

`'type' => \Zend\Session\Storage\ArrayStorage::class,`

**Comment by exptom** [comment]
I've been having the same issue and have opened PR #57 to resolve it.

**Comment by roelvanduijnhoven** [comment]
For what it's worth, I fixed this by removing the following line from our code-base. Seems to work so far.

> Container::setDefaultManager($sm->get('Zend\Session\SessionManager'));

**Comment by exptom** [comment]
zend-session v2.8.1 has just been tagged and should resolve the issue.
