### ISSUE TITLE
 Class Validator\Id is not compatible with PHP 7.1

### ISSUE THREAD

**Issue by opcou** [zendframework/zend-session#112]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-session/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-session/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Session Id validator uses hash_bits_per_character ini setting to validate the id. This setting is deprecated since PHP 7.1 (http://php.net/manual/en/session.configuration.php#ini.session.hash-bits-per-character). This causes the default validator to fail and starting sessions is not possible with default session config.

### Code to reproduce the issue

```php
$session = $sm->get(\Zend\Session\ManagerInterface::class);
$session->start();
```

### Expected results

Should not throw Session validation failed RuntimeException

### Actual results

Throws validation failed exception

**Comment by digitalStyx** [comment]
Hi, I also have a problem.

I use PHP 7.2.17.
My admin wants to change the **session.sid_bits_per_character** to 6 for security reasons. But unfortunately he can't do this because session_id will be not validate.
