### ISSUE TITLE
EventManager Suggestion

### ISSUE THREAD

**Issue by geggleto** [zendframework/zend-session#13]
In Composer.json you suggest using `zendframework/zend-eventmanager` here
https://github.com/zendframework/zend-session/blob/master/composer.json#L32

But its actually a hard dependency here
`"zendframework/zend-eventmanager": "~2.5",`
https://github.com/zendframework/zend-session/blob/master/composer.json#L17

**Comment by samsonasik** [comment]
I've created PR #14 for it.
