### ISSUE TITLE
PHP 7 and redis session caching: session_regenerate_id(): Failed to create(read) session ID

### ISSUE THREAD

**Issue by aimfeld** [zendframework/zend-session#35]
We have been caching sessions with Redis in our Zend Framework 2 project (using zend-session 2.5.2) on PHP 5.6.

After upgrading from PHP 5.6 to PHP 7.0.4, there was a problem with redis session caching, resulting in the following error when users logged in: `PHP message: PHP Catchable fatal error:  session_regenerate_id(): Failed to create(read) session ID: user`.

We currently use a custom save handler to work around this problem:

```
namespace OurFramework\Session\SaveHandler;

class Cache extends \Zend\Session\SaveHandler\Cache
{    
    public function read($id)
    {
        return (string)parent::read($id);
    }
}
```

Maybe this fix could be added to `Zend\Session\SaveHandler\Cache`.

See this [question on stackoverflow](http://stackoverflow.com/questions/36130603/redis-session-caching-with-php-7-and-zf2-session-object-destruction-failed), and the discussion [here](https://bugs.php.net/bug.php?id=71187).

**Comment by aimfeld** [comment]
This occurs in our dev-environment (laravel homestead) with phpredis version 2.2.8-devphp7 (there is no stable phpredis version for PHP 7 yet).

**Comment by necromant2005** [comment]
The issue in php7 session bug: the session must exist to generate_session_id

**Comment by necromant2005** [comment]
Sent pull request: https://github.com/zendframework/zend-session/pull/41
