### ISSUE TITLE
PHP 7 and redis session caching: Session object destruction failed.

### ISSUE THREAD

**Issue by aimfeld** [zendframework/zend-session#36]
We have been caching sessions with Redis in our Zend Framework 2 project (using zend-session 2.5.2) on PHP 5.6.

After upgrading from PHP 5.6 to PHP 7.0.4, we get PHP warnings like `session_regenerate_id(): Session object destruction failed.  ID: user (path: tcp://host:port?weight=1&amp;timeout=3)` and `session_destroy(): Session object destruction failed` when users are logged out.

When discussing the issue on stackoverflow [here](http://stackoverflow.com/questions/36130603/redis-session-caching-with-php-7-and-zf2-session-object-destruction-failed), it was suggested that this might be a bug in zend-session.

**Comment by sandrokeil** [comment]
Are you using the dev branch of the Redis PHP extension, because there is no "stable" version released yet for PHP 7? How have you installed the Redis PHP extension?

**Comment by aimfeld** [comment]
I just checked, in our dev environment (laravel homestead), we are using the phpredis 2.2.8-devphp7, and we don't get these warnings. In staging (platform.sh), we are using phpredis 2.2.5, which seems not to be fully compatible with PHP 7. I wasn't aware that there is no stable phpredis version for PHP 7, feel free to close this issue.

**Comment by aimfeld** [comment]
We have upgraded to PHP 7.1, zend-session: 2.7.3, and are running phpredis 3.1.0-rc1, but this problem still occurs. I think this issue should be reopened...

**Comment by aimfeld** [comment]
As of zend-session 2.8.0, the issues seems to be resolved, thanks!
