### ISSUE TITLE
Minor bug in Validator\AbstractValidatorChaninEM2

### ISSUE THREAD

**Issue by JPG-Consulting** [zendframework/zend-session#63]
After dwonloading the `GlobalEventManager.php` into the EventManager (v3) although I'm not certain this is the correct way to fix it but I was trying a fast solution... I got a new error

`Fatal error: Declaration of Zend\Session\Validator\AbstractValidatorChainEM2::attach() must be compatible with Zend\EventManager\EventManagerInterface::attach($eventName, callable $listener, $priority = 1)`

The method is missing the `callable` definition:

Current code:

`public function attach($event, $callback = null, $priority = 1)` 

where it should be:

`public function attach($event, callable $callback = null, $priority = 1)`

Using PHP 5.6 on WAMP server.

**Comment by adamlundrigan** [comment]
@The GlobalEventManager and StaticEventManager were removed in EventManager v3 ([ref](https://github.com/zendframework/zend-eventmanager/blob/develop/doc/book/migration/removed.md#globaleventmanager-and-staticeventmanager)).  They cannot be forward-ported into EMv3 this way as (as you've discovered) the public API of the EventManager has been significantly changed between v2 and v3.
