### ISSUE TITLE
Bad prototype

### ISSUE THREAD

**Issue by remicollet** [zendframework/zend-session#74]
Running zend-test test suite against php 7.2

`PHP Fatal error:  Declaration of Zend\Session\AbstractContainer::offsetGet($key) must be compatible with & Zend\Stdlib\ArrayObject::offsetGet($key) in ...
`

Indeed in Zend/Stdlib/ArrayObject.php
`    public function &offsetGet($key)`

and in Zend/Session/AbstractContainer.php
`    public function offsetGet($key)`

yes, really early report ;)

**Comment by Ocramius** [comment]
@remicollet isn't this technically a BC break in PHP 7.2? Did the signature change recently, or is the engine just being more strict about it?

**Comment by remicollet** [comment]
> Did the signature change recently, or is the engine just being more strict about it?

Yes the engine is more strict in 7.2
Technically, you could consider this as a small BC break, BTW, prototype are "really" different, so IMHO, better to report.

**Comment by Ocramius** [comment]
CC-ing in also @saramg: this is a subtle BC break.
While it is worth fixing it here, and it will be fixed, this can be extremely annoying to deal with, and should probably be put into discussion for 7.2...

**Comment by Ocramius** [comment]
CC-ing in also @sgolemon: this is a subtle BC break.
While it is worth fixing it here, and it will be fixed, this can be extremely annoying to deal with, and should probably be put into discussion for 7.2...

**Comment by sgolemon** [comment]
You're always welcome to reopen the discussion (I say reopen, because this kind of BC break was discussed and accepted as reasonable).  However IMO ZF is broken here and should reflect upon its life choices.

**Comment by Slamdunk** [comment]
https://github.com/zendframework/zend-session/pull/78

**Comment by weierophinney** [comment]
This is fixed with the 2.8.0 release.

**Comment by ghost** [comment]
I put "&" at offsetGet function and found for me:

//Zend/Session/AbstractContainer.php line 425
public function &offsetGet($key)

**Comment by sumtsow** [comment]
Perfect!
