### ISSUE TITLE
Custom Session handler doesn't work

### ISSUE THREAD

**Issue by dmitriytestapic** [zendframework/zend-session#76]
I'm trying to use custom session handler using Google Datastore. There is a part of code of main module:

```
    public function onBootstrap(MvcEvent $e)
    {
        $sessionConfig = new SessionConfig();

        $sessionManager = new SessionManager($sessionConfig);

        $sessionConfig->setOptions(
            $e->getApplication()->getServiceManager()->get('Config')['datastore-session']['session']
        );

        $sessionsStorage = $e->getApplication()->getServiceManager()->get('CustomSessionStorage\Storage\CustomStorage');
        $sessionManager->setSaveHandler($sessionsStorage->createHandler());

        $sessionManager->start();

        Container::setDefaultManager($sessionManager);
    }
```

But it doesn't work. Sessions are still using files on server and method "SessionHandlerInterface::open" is never called.

But when I write this code (in the same place onBootstrap), session handler is used and methods "open", "read" etc is used. Why the first code doesn't work?

```
session_write_close();
session_set_save_handler($sessionsStorage->createHandler(), true);
session_save_path('sessions');
session_start();
```

**Comment by dmitriytestapic** [comment]
Is there anybody who can check that?

**Comment by froschdesign** [comment]
@dmitriytestapic 
This is a bug tracker and not a support forum. Please use the forum for your question: https://discourse.zendframework.com/

Thanks!

**Comment by dmitriytestapic** [comment]
@froschdesign 
Maybe it's a bug? I don't know, but it doesn't work. I wrote message in this forum but I'm not sure that I will get answer as soon.

Is my code above correct?

**Comment by froschdesign** [comment]
@dmitriytestapic 
I think it would help, if you add your question to the "Questions" category.

**Comment by froschdesign** [comment]
Moved to the forum: https://discourse.zendframework.com/t/custom-session-handler-doesnt-work/126

**Comment by dmitriytestapic** [comment]
@francisdaigle I've added category "Questions". Thanks

**Comment by dmitriytestapic** [comment]
@francisdaigle The problem isn't solved. It's a bug. The usage was copied from your documentation. What extra data do you need?
