### ISSUE TITLE
"Only variable references should be returned by reference" in AbstractContainer::offsetGet() with non-existing key

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [zendframework/zend-session#81]
The release 2.8.0 changed the signature of `AbstractContainer::offsetGet()` to return the value as a reference (see https://github.com/zendframework/zend-session/commit/7f1cd499c0f116269d88633e7387bf1139294b09).

If offsetGet() is called with a key that doesn't exist in the container then PHP throws the notice: "Only variable references should be returned by reference" because of the `return;` (with obv. no variable in it).

What is the correct solution here? Always call `offsetExists()` before calling `offsetGet()` ? Then what's the purpose of the additional `offsetExists()` check in `AbstractContainer::offsetGet()`?

There was a possible fix from @basselin : https://github.com/zendframework/zend-session/pull/80, but I don't know why he deleted it.

**Comment by basselin** [comment]
I assumed after reflection that this behavior was normal.
Moreover, the class `Zend\Session\Container;` contains valid code.

**Comment by MatthiasKuehneEllerhold** [comment]
Mh, it seems like the only code in `Container` is the fix for the broken (?) Code in `AbstractContainer`. That seems weird.

**Comment by basselin** [comment]
This is the reason why I thought "notice" error might be normal when the variable does not exist ...

**Comment by weierophinney** [comment]
Please read the 2.8 release notes; the change was made as v7.1+ releases of php raise an error due to signature variance (the parent class of the `AbstractContainer` returns by reference). 

As no tests failed when we made the change, we proceeded to release. If you can provide a failing test case - something that worked previously but does not now, and which represents an actual workflow from an application you have - we'll see if we can find another solution.

**Comment by MatthiasKuehneEllerhold** [comment]
I've created a branch (forked from master) with a test case that works in 2.7.x and fails on 2.8.0:
see https://github.com/MatthiasKuehneEllerhold/zend-session/blob/abstract_container_offsetget/test/AbstractContainerTest.php#L66

Proposed solution: Use the Code from `Container::offsetGet()` in `AbstractContainer::offsetGet()` . This would make `Container` a class without any code in it. It would just be a non-abstract version of `AbstractContainer`.

**Comment by MatthiasKuehneEllerhold** [comment]
PR: https://github.com/zendframework/zend-session/pull/102
