### ISSUE TITLE
SessionManager : session_start() creates an incorrect $_SESSION['__ZF'] value

### ISSUE THREAD

**Issue by omageus** [zendframework/zend-session#91]
Hello,

I can't figure out how to fix a session problem.

My session_start() (called in SessionManager.php) as sometimes (on session expire ?) an incorrect behavior : it replaces $_SESSION['__ZF'] with an int (0) and cause 

> Warning: Cannot use a scalar value as an array in \vendor\zendframework\zend session\src\Storage\AbstractSessionArrayStorage.php on line 377

A simple var_dump() in \vendor\zendframework\zend-session\src\SessionManager.php explain this problem.

> var_dump($_SESSION);session_start();var_dump($_SESSION);

First dump:
`
\vendor\zendframework\zend-session\src\SessionManager.php:130:
array (size=1)
'__ZF' => 
    array (size=1)
      '_REQUEST_ACCESS_TIME' => float 1508696181.5502
`

Second dump:
`
\vendor\zendframework\zend-session\src\SessionManager.php:132:
array (size=2)
  '__ZF' => int 0
  ...
`

'__ZF' should always be an array(), I don't understand why and how it becomes an integer there.

My session configuration is pretty simple

`'service_manager' => array(
         'abstract_factories' => array(
                'Zend\Cache\Service\StorageCacheAbstractServiceFactory',
          )
    ),
    'session_config' => [
        'cookie_lifetime' => 60*60*2,     
        'gc_maxlifetime'     => 60*60*24*30, 
    ],
    'session_manager' => [
        'validators' => [
            RemoteAddr::class,
            HttpUserAgent::class,
        ]
    ],
    'session_storage' => [
        'type' => SessionArrayStorage::class
    ],`

Did you notice this ?
How would you patch it please ?

Thanks !!
Have a nice day.

**Comment by blairjordan** [comment]
I've raised this on stackoverflow. Pretty much the same issue (__ZF contains 0 instead of an array): https://stackoverflow.com/questions/47825304/zend-authentication-cannot-use-a-scalar-value-as-an-array

**Comment by SilverioMiranda** [comment]
#105

**Comment by samsonasik** [comment]
@omageus should already fixed at #105
